import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.branches': 'الفروع',
    'nav.contact': 'اتصل بنا',
    'nav.admin': 'لوحة التحكم',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل خروج',
    'nav.profile': 'الملف الشخصي',
    'nav.addresses': 'العناوين',
    'nav.orders': 'طلباتي',
    'nav.favorites': 'المفضلة',
    'nav.cart': 'عربة التسوق',
    'nav.search': 'بحث...',
    'nav.back_to_site': 'العودة للموقع',
    'nav.theme': 'الوضع',
    'nav.language': 'اللغة',
    'admin.dashboard': 'الإحصائيات',
    'admin.products': 'المنتجات',
    'admin.categories': 'الأقسام',
    'admin.orders': 'الطلبات',
    'admin.coupons': 'الكوبونات',
    'admin.banners': 'البانرات',
    'admin.branches': 'الفروع',
    'admin.contacts': 'الرسائل',
    'admin.title': 'لوحة التحكم',
    'admin.quick_links': 'روابط سريعة',
    'admin.best_seller': 'الأكثر مبيعاً',
    'admin.monthly_sales': 'المبيعات الشهرية',
    'admin.order_status': 'حالات الطلبات',
    'admin.sales_by_category': 'المبيعات حسب الأقسام',
    'admin.sold': 'تم بيع',
    'admin.unit': 'وحدة',
    'admin.revenue': 'الإيرادات',
    'admin.products_count': 'المنتجات',
    'admin.categories_count': 'الأقسام',
    'admin.orders_count': 'الطلبات',
    'common.loading': 'جارٍ التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.no_data': 'لا توجد بيانات',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'cart.empty': 'العربة فارغة',
    'cart.total': 'المجموع',
    'cart.checkout': 'إتمام الطلب',
    'cart.quantity': 'الكمية',
    'cart.remove': 'حذف',
    'product.add_to_cart': 'أضف إلى العربة',
    'product.reviews': 'التقييمات',
    'product.add_review': 'أضف تقييمك',
    'product.description': 'الوصف',
    'product.related': 'منتجات مشابهة',
    'favorites.empty': 'لا توجد منتجات في المفضلة',
    'orders.empty': 'لا توجد طلبات',
    'orders.order_number': 'طلب رقم',
    'orders.status': 'الحالة',
    'orders.total': 'الإجمالي',
    'orders.address': 'عنوان الشحن',
    'orders.date': 'التاريخ',
    'profile.title': 'الملف الشخصي',
    'profile.name': 'الاسم',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.save': 'حفظ التغييرات',
    'addresses.title': 'العناوين',
    'addresses.add': 'إضافة عنوان',
    'addresses.edit': 'تعديل',
    'addresses.delete': 'حذف',
    'branches.title': 'فروعنا',
    'branches.address': 'العنوان',
    'branches.phone': 'الهاتف',
    'branches.hours': 'مواعيد العمل',
    'contact.title': 'اتصل بنا',
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال',
    'search.title': 'بحث',
    'search.placeholder': 'ابحث عن منتج...',
    'search.no_results': 'لا توجد نتائج',
    'login.title': 'تسجيل الدخول',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.forgot_password': 'نسيت كلمة المرور؟',
    'login.no_account': 'ليس لديك حساب؟',
    'login.register': 'إنشاء حساب',
    'register.title': 'إنشاء حساب',
    'register.name': 'الاسم',
    'register.email': 'البريد الإلكتروني',
    'register.password': 'كلمة المرور',
    'register.submit': 'إنشاء حساب',
    'register.have_account': 'لديك حساب؟',
    'register.login': 'تسجيل الدخول',
    'verify.title': 'التحقق من البريد الإلكتروني',
    'verify.code': 'أدخل كود التحقق',
    'verify.submit': 'تحقق',
    'verify.resend': 'إعادة إرسال الكود',
    'forgot.title': 'نسيت كلمة المرور',
    'forgot.desc': 'أدخل بريدك الإلكتروني لإرسال كود إعادة التعيين',
    'forgot.submit': 'إرسال الكود',
    'forgot.back': 'العودة إلى تسجيل الدخول',
    'reset.title': 'إعادة تعيين كلمة المرور',
    'reset.code': 'كود التحقق',
    'reset.new_password': 'كلمة المرور الجديدة',
    'reset.confirm_password': 'تأكيد كلمة المرور',
    'reset.submit': 'إعادة تعيين',
    'home.hero.shop_now': 'اكتشف عروضنا',
    'home.categories': 'الأقسام',
    'home.latest_products': 'أحدث المنتجات',
    'home.view_all': 'عرض الكل',
    'checkout.title': 'إتمام الطلب',
    'checkout.address': 'العناوين',
    'checkout.phone': 'رقم الهاتف',
    'checkout.coupon': 'الكوبون',
    'checkout.payment': 'طريقة الدفع',
    'checkout.products': 'المنتجات',
    'checkout.cash_on_delivery': 'الدفع عند الاستلام',
    'checkout.cash_desc': 'ادفع نقداً عند استلام الطلب',
    'checkout.wallet': 'المحفظة',
    'checkout.wallet_desc': 'ادفع عبر التحويل البنكي',
    'checkout.subtotal': 'المجموع',
    'checkout.shipping': 'رسوم التوصيل',
    'checkout.discount': 'الخصم',
    'checkout.total': 'الإجمالي',
    'checkout.place_order': 'تأكيد الطلب',
    'checkout.place_order_loading': 'جارٍ إنشاء الطلب...',
    'checkout.apply': 'تطبيق',
    'checkout.enter_coupon': 'أدخل كود الكوبون',
    'checkout.add_address': 'إضافة عنوان',
    'checkout.no_addresses': 'لا يوجد عناوين',
    'checkout.no_phone': 'يرجى إدخال رقم الهاتف',
    'checkout.no_address_selected': 'يرجى اختيار عنوان',
    'checkout.coupon_applied': 'خصم',
    'checkout.apply_coupon': 'تطبيق',
    'checkout.coupon_applied_success': 'تم تطبيق الكوبون بنجاح',
    'checkout.coupon_invalid': 'كوبون غير صالح',
    'checkout.select_address': 'يرجى اختيار عنوان',
    'checkout.address_not_found': 'العنوان المحدد غير موجود',
    'checkout.enter_phone': 'يرجى إدخال رقم الهاتف',
    'checkout.enter_process_number': 'يرجى إدخال رقم العملية',
    'checkout.upload_proof': 'يرجى رفع صورة إثبات الدفع',
    'checkout.order_created': 'تم إنشاء الطلب بنجاح',
    'checkout.order_failed': 'حدث خطأ أثناء إنشاء الطلب',
    'checkout.phone_placeholder': 'أدخل رقم الهاتف',
    'checkout.quantity_label': 'الكمية:',
    'checkout.default': 'افتراضي',
    'checkout.building': 'مبنى',
    'checkout.floor': 'دور',
    'checkout.address_title_fallback': 'العنوان',
    'checkout.process_number': 'رقم العملية',
    'checkout.process_number_placeholder': 'أدخل رقم العملية البنكية',
    'checkout.proof_image': 'صورة إثبات الدفع',
    'checkout.change_image': 'تغيير الصورة',
    'checkout.choose_image': 'اختيار صورة',
    'checkout.your_phone': 'رقم الهاتف',
    'checkout.coupon_label': 'خصم',
    'addresses.address_name': 'اسم العنوان',
    'addresses.home_work': 'المنزل / العمل',
    'addresses.city': 'المدينة',
    'addresses.area': 'المنطقة',
    'addresses.building': 'رقم المبنى',
    'addresses.floor': 'رقم الطابق',
    'addresses.street': 'تفاصيل الشارع',
    'addresses.default': 'تعيين كعنوان افتراضي',
    'addresses.empty': 'لا توجد عناوين مسجلة',
    'addresses.edit_title': 'تعديل العنوان',
    'addresses.add_title': 'إضافة عنوان جديد',
    'addresses.updated': 'تم تحديث العنوان',
    'addresses.added': 'تم إضافة العنوان',
    'addresses.confirm_delete': 'هل أنت متأكد من حذف هذا العنوان؟',
    'addresses.deleted': 'تم حذف العنوان',
    'addresses.default_badge': 'افتراضي',
    'addresses.building_prefix': 'مبنى',
    'addresses.floor_prefix': 'طابق',
    'branches.empty': 'لا توجد فروع حالياً',
    'branches.view_map': 'عرض على الخريطة',
    'cart.title': 'عربة التسوق',
    'cart.shop_now': 'تسوق الآن',
    'cart.summary': 'ملخص الطلب',
    'cart.subtotal': 'المجموع',
    'cart.shipping': 'رسوم التوصيل',
    'cart.grand_total': 'الإجمالي',
    'cart.continue_shopping': 'متابعة التسوق',
    'cart.error': 'حدث خطأ',
    'cart.removed': 'تمت إزالة المنتج',
    'cart.currency': 'ج.م',
    'contact.send_success': 'تم إرسال رسالتك بنجاح',
    'contact.send_message': 'أرسل لنا رسالة',
    'contact.info': 'معلومات الاتصال',
    'contact.country': 'مصر',
    'contact.message_placeholder': 'رسالتك...',
    'favorites.removed': 'تمت الإزالة من المفضلة',
    'favorites.error': 'حدث خطأ',
    'favorites.login_required': 'يرجى تسجيل الدخول أولاً',
    'favorites.title': 'المفضلة',
    'favorites.browse': 'تصفح المنتجات',
    'forgot.send_success': 'تم إرسال كود إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
    'forgot.send_failed': 'فشل إرسال الكود',
    'home.banner_fallback_title': 'دلورة ماركت',
    'home.banner_fallback_button': 'اكتشف عروضنا',
    'login.success': 'تم تسجيل الدخول بنجاح',
    'login.failed': 'فشل تسجيل الدخول',
    'login.welcome': 'أهلاً بك مرة أخرى في دلورة ماركت',
    'login.loading': 'جارٍ تسجيل الدخول...',
    'notifications.title': 'الإشعارات',
    'notifications.mark_all_read': 'تحديد الكل كمقروء',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.browse': 'تصفح المنتجات',
    'orders.pending': 'قيد الانتظار',
    'orders.confirmed': 'مؤكد',
    'orders.processing': 'قيد المعالجة',
    'orders.out_for_delivery': 'خرج للتوصيل',
    'orders.delivered': 'تم التوصيل',
    'orders.cancelled': 'ملغي',
    'orders.completed': 'مكتمل',
    'orders.order_prefix': 'طلب #',
    'orders.currency': 'ج.م',
    'orders.payment_cash': 'الدفع عند الاستلام',
    'orders.payment_wallet': 'المحفظة',
    'orders.payment_paid': 'مدفوع',
    'orders.payment_failed': 'فشل',
    'orders.payment_pending': 'قيد الانتظار',
    'orders.shipping_address': 'عنوان الشحن:',
    'product.login_required': 'يرجى تسجيل الدخول أولاً',
    'product.added_to_cart': 'تمت الإضافة إلى العربة',
    'product.review_added': 'تم إضافة التقييم',
    'product.not_found': 'المنتج غير موجود',
    'product.brand': 'العلامة التجارية:',
    'product.offer_until_stock': 'العرض حتى نفاد الكمية',
    'product.offer_limited': 'عرض لفترة محدودة',
    'product.max_quantity': 'الحد الأقصى:',
    'product.review_placeholder': 'اكتب تقييمك...',
    'product.submitting': 'جارٍ الإرسال...',
    'product.submit_review': 'إرسال التقييم',
    'product.no_reviews': 'لا توجد تقييمات بعد',
    'product.user_fallback': 'مستخدم',
    'product.adding': 'جارٍ الإضافة...',
    'product.breadcrumb_home': 'الرئيسية',
    'product.breadcrumb_products': 'المنتجات',
    'products.title': 'المنتجات',
    'products.filter': 'تصفية',
    'products.hide': 'إخفاء',
    'products.search': 'بحث...',
    'products.categories': 'الأقسام',
    'products.all': 'الكل',
    'products.sort': 'الترتيب',
    'products.newest': 'الأحدث',
    'products.price_low': 'السعر: الأقل أولاً',
    'products.price_high': 'السعر: الأعلى أولاً',
    'products.name_az': 'الاسم: أ-ي',
    'products.count': 'منتج',
    'products.empty': 'لا توجد منتجات متاحة',
    'products.filter_button': 'تصفية',
    'profile.updated': 'تم تحديث الملف الشخصي',
    'profile.full_name': 'الاسم الكامل',
    'profile.gender': 'الجنس',
    'profile.male': 'ذكر',
    'profile.female': 'أنثى',
    'profile.role': 'الدور',
    'profile.customer': 'عميل',
    'profile.saving': 'جارٍ الحفظ...',
    'register.success': 'تم إنشاء الحساب بنجاح',
    'register.failed': 'فشل إنشاء الحساب',
    'register.subtitle': 'انضم إلى دلورة ماركت واستمتع بالتسوق',
    'register.full_name': 'الاسم الكامل',
    'register.name_placeholder': 'محمد أحمد',
    'register.gender': 'الجنس',
    'register.male': 'ذكر',
    'register.female': 'أنثى',
    'register.loading': 'جارٍ إنشاء الحساب...',

    'reset.password_mismatch': 'كلمة المرور غير متطابقة',
    'reset.success': 'تم إعادة تعيين كلمة المرور بنجاح',
    'reset.failed': 'فشل إعادة التعيين',
    'reset.verify_code': 'كود التحقق',
    'reset.enter_code': 'أدخل الكود',
    'reset.loading': 'جارٍ إعادة التعيين...',
    'verify.success': 'تم التحقق من البريد الإلكتروني بنجاح',
    'verify.failed': 'فشل التحقق',
    'verify.code_resent': 'تم إعادة إرسال الكود',
    'verify.description': 'أدخل كود التحقق المرسل إلى',
    'verify.your_email': 'بريدك الإلكتروني',
    'verify.loading': 'جارٍ التحقق...',
    'footer.brand_subtitle': 'تسوق بسهولة مع أكبر هايبر ماركت في مصر. نوفر لك كل احتياجاتك المنزلية بأفضل الأسعار.',
    'footer.quick_links': 'روابط سريعة',
    'footer.my_account': 'حسابي',
    'footer.contact_info': 'معلومات الاتصال',
    'footer.country': 'مصر',
    'footer.copyright': 'دلورة ماركت. جميع الحقوق محفوظة.',
    'footer.home': 'الرئيسية',
    'footer.products': 'المنتجات',
    'footer.branches': 'الفروع',
    'footer.contact': 'اتصل بنا',
    'footer.profile': 'الملف الشخصي',
    'footer.orders': 'طلباتي',
    'footer.cart': 'عربة التسوق',
    'footer.favorites': 'المفضلة',
    'nav.notifications': 'الإشعارات',
    'nav.brand': 'دلورة',
    'nav.brand_sub': 'ماركت',
    'nav.arabic': 'العربية',
    'product_card.offer': 'عرض',
    'product_card.add': 'أضف',
    'product_card.currency': 'ج.م',
    'product_card.login_required': 'يرجى تسجيل الدخول أولاً',
    'product_card.added': 'تمت الإضافة إلى العربة',
    'common.unexpected_error': 'حدث خطأ غير متوقع',
    'common.or': 'أو',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.branches': 'Branches',
    'nav.contact': 'Contact Us',
    'nav.admin': 'Dashboard',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.addresses': 'Addresses',
    'nav.orders': 'My Orders',
    'nav.favorites': 'Favorites',
    'nav.cart': 'Cart',
    'nav.search': 'Search...',
    'nav.back_to_site': 'Back to Site',
    'nav.theme': 'Theme',
    'nav.language': 'Language',
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.categories': 'Categories',
    'admin.orders': 'Orders',
    'admin.coupons': 'Coupons',
    'admin.banners': 'Banners',
    'admin.branches': 'Branches',
    'admin.contacts': 'Messages',
    'admin.title': 'Dashboard',
    'admin.quick_links': 'Quick Links',
    'admin.best_seller': 'Best Seller',
    'admin.monthly_sales': 'Monthly Sales',
    'admin.order_status': 'Order Status',
    'admin.sales_by_category': 'Sales by Category',
    'admin.sold': 'Sold',
    'admin.unit': 'units',
    'admin.revenue': 'Revenue',
    'admin.products_count': 'Products',
    'admin.categories_count': 'Categories',
    'admin.orders_count': 'Orders',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.no_data': 'No data available',
    'footer.rights': 'All rights reserved.',
    'cart.empty': 'Cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.quantity': 'Qty',
    'cart.remove': 'Remove',
    'product.add_to_cart': 'Add to Cart',
    'product.reviews': 'Reviews',
    'product.add_review': 'Add Your Review',
    'product.description': 'Description',
    'product.related': 'Related Products',
    'favorites.empty': 'No favorites yet',
    'orders.empty': 'No orders yet',
    'orders.order_number': 'Order #',
    'orders.status': 'Status',
    'orders.total': 'Total',
    'orders.address': 'Shipping Address',
    'orders.date': 'Date',
    'profile.title': 'Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.save': 'Save Changes',
    'addresses.title': 'Addresses',
    'addresses.add': 'Add Address',
    'addresses.edit': 'Edit',
    'addresses.delete': 'Delete',
    'branches.title': 'Our Branches',
    'branches.address': 'Address',
    'branches.phone': 'Phone',
    'branches.hours': 'Working Hours',
    'contact.title': 'Contact Us',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send',
    'search.title': 'Search',
    'search.placeholder': 'Search for a product...',
    'search.no_results': 'No results found',
    'login.title': 'Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.forgot_password': 'Forgot Password?',
    'login.no_account': "Don't have an account?",
    'login.register': 'Create Account',
    'register.title': 'Create Account',
    'register.name': 'Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.submit': 'Register',
    'register.have_account': 'Already have an account?',
    'register.login': 'Login',
    'verify.title': 'Verify Email',
    'verify.code': 'Enter verification code',
    'verify.submit': 'Verify',
    'verify.resend': 'Resend Code',
    'forgot.title': 'Forgot Password',
    'forgot.desc': 'Enter your email to receive reset code',
    'forgot.submit': 'Send Code',
    'forgot.back': 'Back to Login',
    'reset.title': 'Reset Password',
    'reset.code': 'Verification Code',
    'reset.new_password': 'New Password',
    'reset.confirm_password': 'Confirm Password',
    'reset.submit': 'Reset',
    'home.hero.shop_now': 'Discover Our Offers',
    'home.categories': 'Categories',
    'home.latest_products': 'Latest Products',
    'home.view_all': 'View All',
    'checkout.title': 'Checkout',
    'checkout.address': 'Address',
    'checkout.phone': 'Phone Number',
    'checkout.coupon': 'Coupon',
    'checkout.payment': 'Payment Method',
    'checkout.products': 'Products',
    'checkout.cash_on_delivery': 'Cash on Delivery',
    'checkout.cash_desc': 'Pay cash when you receive',
    'checkout.wallet': 'Wallet',
    'checkout.wallet_desc': 'Pay via bank transfer',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.discount': 'Discount',
    'checkout.total': 'Total',
    'checkout.place_order': 'Place Order',
    'checkout.place_order_loading': 'Processing...',
    'checkout.apply': 'Apply',
    'checkout.enter_coupon': 'Enter coupon code',
    'checkout.add_address': 'Add Address',
    'checkout.no_addresses': 'No addresses found',
    'checkout.no_phone': 'Please enter your phone number',
    'checkout.no_address_selected': 'Please select an address',
    'checkout.coupon_applied': 'off',
    'checkout.apply_coupon': 'Apply',
    'checkout.coupon_applied_success': 'Coupon applied successfully',
    'checkout.coupon_invalid': 'Invalid coupon',
    'checkout.select_address': 'Please select an address',
    'checkout.address_not_found': 'Selected address not found',
    'checkout.enter_phone': 'Please enter your phone number',
    'checkout.enter_process_number': 'Please enter the process number',
    'checkout.upload_proof': 'Please upload payment proof image',
    'checkout.order_created': 'Order created successfully',
    'checkout.order_failed': 'Error creating order',
    'checkout.phone_placeholder': 'Enter phone number',
    'checkout.quantity_label': 'Qty:',
    'checkout.default': 'Default',
    'checkout.building': 'Bldg',
    'checkout.floor': 'Floor',
    'checkout.address_title_fallback': 'Address',
    'checkout.process_number': 'Process Number',
    'checkout.process_number_placeholder': 'Enter bank process number',
    'checkout.proof_image': 'Payment Proof Image',
    'checkout.change_image': 'Change Image',
    'checkout.choose_image': 'Choose Image',
    'checkout.your_phone': 'Phone Number',
    'checkout.coupon_label': 'off',
    'addresses.address_name': 'Address Name',
    'addresses.home_work': 'Home / Work',
    'addresses.city': 'City',
    'addresses.area': 'Area',
    'addresses.building': 'Building Number',
    'addresses.floor': 'Floor Number',
    'addresses.street': 'Street Details',
    'addresses.default': 'Set as default address',
    'addresses.empty': 'No addresses saved',
    'addresses.edit_title': 'Edit Address',
    'addresses.add_title': 'Add New Address',
    'addresses.updated': 'Address updated',
    'addresses.added': 'Address added',
    'addresses.confirm_delete': 'Are you sure you want to delete this address?',
    'addresses.deleted': 'Address deleted',
    'addresses.default_badge': 'Default',
    'addresses.building_prefix': 'Bldg',
    'addresses.floor_prefix': 'Floor',
    'branches.empty': 'No branches yet',
    'branches.view_map': 'View on Map',
    'cart.title': 'Shopping Cart',
    'cart.shop_now': 'Shop Now',
    'cart.summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.grand_total': 'Total',
    'cart.continue_shopping': 'Continue Shopping',
    'cart.error': 'An error occurred',
    'cart.removed': 'Product removed',
    'cart.currency': 'EGP',
    'contact.send_success': 'Your message has been sent successfully',
    'contact.send_message': 'Send Us a Message',
    'contact.info': 'Contact Information',
    'contact.country': 'Egypt',
    'contact.message_placeholder': 'Your message...',
    'favorites.removed': 'Removed from favorites',
    'favorites.error': 'An error occurred',
    'favorites.login_required': 'Please login first',
    'favorites.title': 'Favorites',
    'favorites.browse': 'Browse Products',
    'forgot.send_success': 'Password reset code has been sent to your email',
    'forgot.send_failed': 'Failed to send code',
    'home.banner_fallback_title': 'Delora Market',
    'home.banner_fallback_button': 'Discover Our Offers',
    'login.success': 'Login successful',
    'login.failed': 'Login failed',
    'login.welcome': 'Welcome back to Delora Market',
    'login.loading': 'Logging in...',
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Mark All as Read',
    'notifications.empty': 'No notifications',
    'notifications.browse': 'Browse Products',
    'orders.pending': 'Pending',
    'orders.confirmed': 'Confirmed',
    'orders.processing': 'Processing',
    'orders.out_for_delivery': 'Out for Delivery',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
    'orders.completed': 'Completed',
    'orders.order_prefix': 'Order #',
    'orders.currency': 'EGP',
    'orders.payment_cash': 'Cash on Delivery',
    'orders.payment_wallet': 'Wallet',
    'orders.payment_paid': 'Paid',
    'orders.payment_failed': 'Failed',
    'orders.payment_pending': 'Pending',
    'orders.shipping_address': 'Shipping Address:',
    'product.login_required': 'Please login first',
    'product.added_to_cart': 'Added to cart',
    'product.review_added': 'Review added',
    'product.not_found': 'Product not found',
    'product.brand': 'Brand:',
    'product.offer_until_stock': 'Offer until stock runs out',
    'product.offer_limited': 'Limited time offer',
    'product.max_quantity': 'Max:',
    'product.review_placeholder': 'Write your review...',
    'product.submitting': 'Submitting...',
    'product.submit_review': 'Submit Review',
    'product.no_reviews': 'No reviews yet',
    'product.user_fallback': 'User',
    'product.adding': 'Adding...',
    'product.breadcrumb_home': 'Home',
    'product.breadcrumb_products': 'Products',
    'products.title': 'Products',
    'products.filter': 'Filter',
    'products.hide': 'Hide',
    'products.search': 'Search...',
    'products.categories': 'Categories',
    'products.all': 'All',
    'products.sort': 'Sort By',
    'products.newest': 'Newest',
    'products.price_low': 'Price: Low to High',
    'products.price_high': 'Price: High to Low',
    'products.name_az': 'Name: A-Z',
    'products.count': 'product',
    'products.empty': 'No products available',
    'products.filter_button': 'Filter',
    'profile.updated': 'Profile updated',
    'profile.full_name': 'Full Name',
    'profile.gender': 'Gender',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.role': 'Role',
    'profile.customer': 'Customer',
    'profile.saving': 'Saving...',
    'register.success': 'Account created successfully',
    'register.failed': 'Account creation failed',
    'register.subtitle': 'Join Delora Market and enjoy shopping',
    'register.full_name': 'Full Name',
    'register.name_placeholder': 'John Doe',
    'register.gender': 'Gender',
    'register.male': 'Male',
    'register.female': 'Female',
    'register.loading': 'Creating account...',
    'reset.password_mismatch': 'Passwords do not match',
    'reset.success': 'Password reset successfully',
    'reset.failed': 'Reset failed',
    'reset.verify_code': 'Verification Code',
    'reset.enter_code': 'Enter code',
    'reset.loading': 'Resetting...',
    'verify.success': 'Email verified successfully',
    'verify.failed': 'Verification failed',
    'verify.code_resent': 'Code resent',
    'verify.description': 'Enter the verification code sent to',
    'verify.your_email': 'your email',
    'verify.loading': 'Verifying...',
    'footer.brand_subtitle': 'Shop easily with the largest hypermarket in Egypt. We provide all your home needs at the best prices.',
    'footer.quick_links': 'Quick Links',
    'footer.my_account': 'My Account',
    'footer.contact_info': 'Contact Info',
    'footer.country': 'Egypt',
    'footer.copyright': 'Delora Market. All rights reserved.',
    'footer.home': 'Home',
    'footer.products': 'Products',
    'footer.branches': 'Branches',
    'footer.contact': 'Contact Us',
    'footer.profile': 'Profile',
    'footer.orders': 'My Orders',
    'footer.cart': 'Cart',
    'footer.favorites': 'Favorites',
    'nav.notifications': 'Notifications',
    'nav.brand': 'Delora',
    'nav.brand_sub': 'Market',
    'nav.arabic': 'English',
    'product_card.offer': 'Offer',
    'product_card.add': 'Add',
    'product_card.currency': 'EGP',
    'product_card.login_required': 'Please login first',
    'product_card.added': 'Added to cart',
    'common.unexpected_error': 'An unexpected error occurred',
    'common.or': 'Or',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('delora-lang') || 'ar'; } catch { return 'ar'; }
  });

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    try { localStorage.setItem('delora-lang', lang); } catch {}
  }, [lang]);

  const t = useCallback((key) => translations[lang]?.[key] || key, [lang]);

  const toggleLanguage = () => setLang((prev) => (prev === 'ar' ? 'en' : 'ar'));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
